server:
  port: 0 #Gera randomicamente uma porta aleatória.

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value} }

spring:
  application:
    name: ms-application
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/aw_healthy_app?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        appCreatedSupplier-out-0:
          destination: app.v1.event.app-created
        appUpdatedSupplier-out-0:
          destination: app.v1.event.app-updated