spring:
  application:
    name: ms-gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
  
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    server-url:
      defaultZone: http://localhost:8761/eureka
